name: notebook
channels:
  - conda-forge
dependencies:
  - python
  - ase==3.26.*
  - edrixs
  - h5py==3.14.*
  - ipympl
  - ipywidgets
  - lmfit
  - matplotlib==3.10.*
  - pymca==5.9.*
  - pillow
  - pip
  - pip:
      - pymcaspec
